# Generated by Django 6.0.3 on 2026-03-04 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_blocks',
            field=models.CharField(blank=True, help_text='Các khối thi, ví dụ: A00;A01', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, help_text='Ví dụ: Toán 12, Vật lý 12', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='course_thumbnails/'),
        ),
    ]
